# Generated by Django 4.0.6 on 2022-07-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
