# Generated by Django 4.0.6 on 2022-12-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_userinformation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
